#!/usr/bin/env python3
"""Build a self-contained HTML explorer from PlusCal model traces.

Architecture (v3):
    <model>.pcal        — formal spec (PlusCal golden source)
    <model>.tla         — generated by pcal.trans (DO NOT EDIT)
    tlc_sweep.py        — TLC → distrib/traces/*.puml
    build.py            — unified CLI (sweep / build / deploy)

This script assembles everything into distrib/index.html:
  1. Reads distrib/traces/*.puml (PlantUML text from sweep)
  2. Embeds PlantUML text in ALL_TRACES (rendered client-side via PlantUML server)
  3. Generates controls HTML (cascading dropdowns)
  4. Outputs: distrib/index.html (self-contained)

Usage:
    python build_explorer.py
    python build_explorer.py --serve
"""
from __future__ import annotations

import argparse
import datetime
import shutil
import json
import re
import subprocess
import sys
import zipfile
from http.server import HTTPServer, SimpleHTTPRequestHandler
from pathlib import Path

# ═══════════════════════════════════════════════════════════════════════
# Paths
# ═══════════════════════════════════════════════════════════════════════
SCRIPT_DIR    = Path(__file__).resolve().parent
DISTRIB_DIR   = SCRIPT_DIR / "distrib"
TRACES_DIR    = DISTRIB_DIR / "puml"

OUTPUT_HTML   = DISTRIB_DIR / "index.html"

# Suppress console window flash on Windows for subprocess calls
_NOWIN = {"creationflags": subprocess.CREATE_NO_WINDOW} if sys.platform == "win32" else {}


# ═══════════════════════════════════════════════════════════════════════
# Helpers
# ═══════════════════════════════════════════════════════════════════════

def load_traces(constant_names: list[str] = None) -> dict:
    """Load all trace .puml files and expand aliases.

    Each entry in the returned dict has:
      - puml_text: str  (PlantUML source)
      - parameters: dict (reconstructed from filename tag)
    """
    if constant_names is None:
        constant_names = []
    traces = {}
    for f in sorted(TRACES_DIR.glob("*.puml")):
        if f.stem.startswith("_"):
            continue
        key = f.stem
        puml_text = f.read_text(encoding="utf-8")
        parts = key.split(".")
        parameters = dict(zip(constant_names, parts)) if constant_names else {}
        traces[key] = {"puml_text": puml_text, "parameters": parameters}

    # Expand aliases: { aliased_key: canonical_key }
    alias_file = TRACES_DIR / "_aliases.json"
    if alias_file.exists():
        aliases = json.loads(alias_file.read_text(encoding="utf-8"))
        for alias_key, canonical_key in aliases.items():
            if alias_key not in traces and canonical_key in traces:
                parts = alias_key.split(".")
                parameters = dict(zip(constant_names, parts)) if constant_names else {}
                traces[alias_key] = {
                    "puml_text": traces[canonical_key]["puml_text"],
                    "parameters": parameters,
                }

    return traces


def build_flow_tree(traces: dict, constant_names: list[str]) -> dict:
    """Build nested dict from trace parameters, generic for any set of constants.

    For N constants, builds an N-level nested dict where each level corresponds
    to one constant (in order).  The leaf level is a list of values for the
    last constant.

    Example for MESI (Operation, InitState, RemoteState):
        {
            "Read": {"I": ["M", "E", "S", "I"], "M": ["I"], ...},
            "Write": {"I": ["M", "E", "S", "I"], ...},
        }
    """
    if not constant_names:
        return {}
    tree: dict = {}
    for key, data in traces.items():
        p = data["parameters"]
        vals = [p.get(c, "") for c in constant_names]
        if not all(vals):
            continue
        # Walk/create nested dicts for all but last constant
        node = tree
        for v in vals[:-1]:
            node = node.setdefault(v, {})
        # Last level is a list
        if not isinstance(node.get(vals[-1]), list):
            if vals[-1] not in node:
                node[vals[-1]] = True  # leaf marker
        # We also want to record the trace exists for this combo
        # Actually, for N=1 the tree is {val: True}, for N>1 last level is a list
    # Simpler approach: just record all combos as tag -> True, and let JS handle it
    # Actually let me do this cleanly:
    tree = {}
    for key, data in traces.items():
        p = data["parameters"]
        vals = [p.get(c, "") for c in constant_names]
        if not all(vals):
            continue
        if len(vals) == 1:
            tree.setdefault(vals[0], True)
        else:
            node = tree
            for v in vals[:-2]:
                node = node.setdefault(v, {})
            # Second-to-last level maps to list of last values
            node.setdefault(vals[-2], [])
            if vals[-1] not in node[vals[-2]]:
                node[vals[-2]].append(vals[-1])
    return tree


def build_full_flow_tree(config) -> dict:
    """Build nested dict from ALL constant combos (cartesian product).

    Unlike build_flow_tree() which only includes combos with traces,
    this includes every combination so dropdowns are fully populated.
    """
    constant_names = config.constant_names
    if not constant_names:
        return {}
    tree: dict = {}
    for combo in config.all_combos():
        vals = [str(v) for v in combo]
        if len(vals) == 1:
            tree.setdefault(vals[0], True)
        else:
            node = tree
            for v in vals[:-2]:
                node = node.setdefault(v, {})
            node.setdefault(vals[-2], [])
            if vals[-1] not in node[vals[-2]]:
                node[vals[-2]].append(vals[-1])
    return tree


# ═══════════════════════════════════════════════════════════════════════
# ═══════════════════════════════════════════════════════════════════════
# Branding helpers (read from explorer.json config)
# ═══════════════════════════════════════════════════════════════════════

def _render_branding_footer(branding: dict) -> str:
    """Render the branding block (classification, contact, AI disclaimer).
    Returns empty string if branding is empty/None — clean for open-source models."""
    if not branding:
        return ""
    parts = []
    parts.append('<div style="margin-top:10px; padding-top:8px; border-top:1px solid #334155;">')
    classification = branding.get("classification")
    if classification:
        color = branding.get("classificationColor", "#f85149")
        parts.append(f'<div style="font-weight:700; color:{color}; letter-spacing:1px; font-size:11px; text-transform:uppercase;">{classification}</div>')
    contact = branding.get("contact")
    if contact:
        label = contact.get("label", "Contact")
        email = contact.get("email", "")
        if email:
            parts.append(f'<div style="margin-top:2px;">{label} <a href="mailto:{email}" style="color:#7dd3fc; text-decoration:none;">{email}</a></div>')
    ai_disclaimer = branding.get("aiDisclaimer")
    if ai_disclaimer:
        parts.append(f'<div style="margin-top:4px; font-style:italic; font-size:10px; line-height:1.4;">{ai_disclaimer}</div>')
    parts.append('</div>')
    return "\n".join(parts)


def _render_footer_links(branding: dict) -> str:
    """Render footer links from branding config (custom links)."""
    if not branding:
        return ""
    parts = []
    footer_links = branding.get("footerLinks", [])
    for link in footer_links:
        label = link.get("label", "")
        url = link.get("url", "")
        if label and url:
            parts.append(f'<a href="{url}" style="color:#7dd3fc; text-decoration:none;" target="_blank">&#128214; {label}</a><br>')
    return "\n".join(parts)


# ═══════════════════════════════════════════════════════════════════════
# Documentation builder (Markdown → self-contained HTML)
# ═══════════════════════════════════════════════════════════════════════

def build_documentation_html(md_path: Path, title: str = "Documentation",
                             branding: dict | None = None) -> str:
    """Convert a Markdown file to a styled, self-contained HTML page.

    Uses the Python `markdown` library with common extensions.
    Falls back to a simple <pre> block if `markdown` is not installed.
    """
    md_text = md_path.read_text(encoding="utf-8")

    try:
        import markdown
        body = markdown.markdown(
            md_text,
            extensions=["tables", "fenced_code", "codehilite", "toc", "sane_lists"],
            extension_configs={"codehilite": {"css_class": "highlight", "guess_lang": False}},
        )
    except ImportError:
        # Graceful fallback — wrap raw markdown in <pre>
        import html as _html
        body = f"<pre>{_html.escape(md_text)}</pre>"

    branding_footer = _render_branding_footer(branding) if branding else ""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
*, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
html {{ height: 100%; }}
body {{
  min-height: 100%;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  color: #c9d1d9; background: #0d1117;
  line-height: 1.7; font-size: 15px;
}}
.topbar {{
  display: flex; align-items: center; justify-content: space-between;
  height: 48px; padding: 0 20px;
  background: #1e293b; color: #e2e8f0;
}}
.topbar h1 {{ font-size: 16px; font-weight: 600; letter-spacing: 0.5px; }}
.topbar a {{ color: #7dd3fc; text-decoration: none; font-size: 13px; }}
.topbar a:hover {{ text-decoration: underline; }}
.content {{
  max-width: 900px; margin: 0 auto; padding: 32px 24px 64px;
}}
h1 {{ font-size: 28px; margin: 32px 0 16px; color: #e2e8f0; border-bottom: 1px solid #30363d; padding-bottom: 8px; }}
h2 {{ font-size: 22px; margin: 28px 0 12px; color: #e2e8f0; border-bottom: 1px solid #21262d; padding-bottom: 6px; }}
h3 {{ font-size: 17px; margin: 24px 0 8px; color: #e2e8f0; }}
p {{ margin: 8px 0; }}
a {{ color: #58a6ff; text-decoration: none; }}
a:hover {{ text-decoration: underline; }}
ul, ol {{ padding-left: 24px; margin: 8px 0; }}
li {{ margin: 4px 0; }}
code {{
  background: #161b22; padding: 2px 6px; border-radius: 4px;
  font-size: 13px; color: #a5f3fc;
  font-family: "Cascadia Code", "Fira Code", Consolas, monospace;
}}
pre {{
  background: #161b22; padding: 14px 16px; border-radius: 8px;
  overflow-x: auto; margin: 12px 0; border: 1px solid #30363d;
}}
pre code {{ background: none; padding: 0; font-size: 13px; color: #c9d1d9; }}
table {{
  border-collapse: collapse; width: 100%; margin: 12px 0;
  font-size: 14px;
}}
th, td {{
  padding: 8px 12px; text-align: left;
  border: 1px solid #30363d;
}}
th {{ background: #161b22; color: #e2e8f0; font-weight: 600; }}
td {{ color: #c9d1d9; }}
tr:nth-child(even) td {{ background: #0d1117; }}
tr:nth-child(odd) td {{ background: #161b22; }}
hr {{ border: none; border-top: 1px solid #30363d; margin: 24px 0; }}
blockquote {{
  border-left: 3px solid #3b82f6; padding: 8px 16px; margin: 12px 0;
  color: #8b949e; background: #161b22; border-radius: 0 6px 6px 0;
}}
.highlight pre {{ background: #161b22; }}
.branding {{ max-width: 900px; margin: 0 auto; padding: 0 24px 32px; }}
</style>
</head>
<body>
<div class="topbar">
  <h1>{title}</h1>
  <a href="index.html">&larr; Back to Explorer</a>
</div>
<div class="content">
{body}
</div>
{f'<div class="branding">{branding_footer}</div>' if branding_footer else ''}
</body>
</html>"""


# ═══════════════════════════════════════════════════════════════════════
# HTML Template
# ═══════════════════════════════════════════════════════════════════════

def build_html(
    all_traces: dict,
    flow_tree: dict,
    pcal_source: str = "",
    **kwargs,
) -> str:
    """Assemble the complete self-contained index.html."""

    title = kwargs.get("title", "Flow Explorer")
    branding = kwargs.get("branding") or {}
    pcal_filename = kwargs.get("pcal_filename", "model.pcal")
    constant_names = kwargs.get("constant_names", [])
    plantuml_server = kwargs.get("plantuml_server", "")
    tlc_server = kwargs.get("tlc_server", "http://127.0.0.1:18080")
    channel_styles = kwargs.get("channel_styles", {})
    participants = kwargs.get("participants", [])
    invalid_combos = kwargs.get("invalid_combos", [])
    skipped_combos = kwargs.get("skipped_combos", [])

    # Build config-driven sidebar dropdowns
    dropdown_html_parts = []
    for i, cname in enumerate(constant_names):
        sel_id = f"sel-const-{i}"
        if i > 0:
            dropdown_html_parts.append('      <div style="height:8px"></div>')
        dropdown_html_parts.append(f'      <label for="{sel_id}">{cname}</label>')
        dropdown_html_parts.append(f'      <select id="{sel_id}"></select>')
    dropdowns_html = "\n".join(dropdown_html_parts)

    # Channel legend visible if global channel_styles are configured
    has_channels = bool(channel_styles)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="0">
<!-- Built: {datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")} -->
<title>{title}</title>
<style>
/* ── Reset & base ─────────────────────────────────────── */
*, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
html, body {{ height: 100%; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; color: #c9d1d9; background: #0d1117; }}

/* ── Top bar ──────────────────────────────────────────── */
.topbar {{ display: flex; align-items: center; justify-content: space-between; height: 48px; padding: 0 20px; background: #1e293b; color: #e2e8f0; }}
.topbar h1 {{ font-size: 16px; font-weight: 600; letter-spacing: 0.5px; }}
.topbar-right {{ display: flex; align-items: center; gap: 12px; font-size: 13px; }}
.badge {{ display: inline-block; padding: 1px 7px; border-radius: 10px; font-size: 11px; font-weight: 600; }}
.badge-static {{ background: #334155; color: #94a3b8; }}
.badge-live {{ background: #065f46; color: #6ee7b7; }}
.flow-count {{ color: #94a3b8; font-size: 12px; }}

/* ── Layout ───────────────────────────────────────────── */
.main-layout {{ display: grid; grid-template-columns: 280px 1fr; height: calc(100vh - 48px); }}
.content-area {{ display: flex; flex-direction: row; overflow: hidden; }}

/* ── Sidebar ──────────────────────────────────────────── */
.sidebar {{ background: #1a1a2e; color: #cbd5e1; overflow-y: auto; padding: 16px; display: flex; flex-direction: column; gap: 20px; }}
.sidebar h2 {{ font-size: 12px; text-transform: uppercase; letter-spacing: 1px; color: #94a3b8; margin-bottom: 8px; }}
.sidebar label {{ display: block; font-size: 13px; margin-bottom: 4px; color: #e2e8f0; }}
.sidebar select {{ width: 100%; padding: 6px 10px; border-radius: 6px; border: 1px solid #334155; background: #0f172a; color: #e2e8f0; font-size: 13px; outline: none; }}
.sidebar select:focus {{ border-color: #3b82f6; }}
.sidebar .btn {{ display: inline-flex; align-items: center; justify-content: center; padding: 7px 14px; border-radius: 6px; border: none; font-size: 13px; cursor: pointer; transition: background 0.15s; width: 100%; margin-top: 4px; }}
.btn-secondary {{ background: #334155; color: #e2e8f0; }}
.btn-secondary:hover {{ background: #475569; }}
.btn-sm {{ padding: 5px 10px; font-size: 12px; width: auto; }}
.checkbox-row {{ display: flex; align-items: center; gap: 8px; font-size: 13px; cursor: pointer; }}
.checkbox-row input {{ accent-color: #3b82f6; }}
.sidebar hr {{ border: none; border-top: 1px solid #334155; }}

/* ── Legend ────────────────────────────────────────────── */
.legend {{ display: flex; flex-wrap: wrap; gap: 8px 14px; padding: 10px 0; }}
.legend-item {{ display: flex; align-items: center; gap: 5px; font-size: 11px; color: #94a3b8; }}
.legend-swatch {{ width: 20px; height: 3px; border-radius: 1px; }}

/* ── Right pane (diagram area) ────────────────────────── */
.diagram-pane {{ display: flex; flex-direction: column; background: #ffffff; overflow: hidden; flex: 3; min-width: 0; }}
.diagram-header {{ display: flex; align-items: center; justify-content: space-between; padding: 8px 14px; background: #f6f8fa; border-bottom: 1px solid #d0d7de; min-height: 40px; gap: 6px; flex-shrink: 0; }}
.diagram-header span {{ font-size: 13px; font-weight: 600; color: #1f2328; }}
.diagram-toolbar {{ display: flex; gap: 4px; }}

/* ── Single diagram view ──────────────────────────────── */
.diagram-container {{ flex: 1; overflow: auto; padding: 16px; position: relative; }}
.no-diagram {{ color: #656d76; font-style: italic; padding: 40px; text-align: center; }}
.combo-status {{ display: flex; flex-direction: column; align-items: center; justify-content: center; padding: 48px 24px; text-align: center; gap: 8px; }}
.combo-status-icon {{ font-size: 36px; }}
.combo-status p {{ margin: 0; line-height: 1.6; }}
.combo-invalid {{ color: #f85149; }}
.combo-invalid p {{ color: #f85149; }}
.combo-skipped {{ color: #d29922; }}
.combo-skipped p {{ color: #d29922; }}

/* ── Trace table ──────────────────────────────────────── */
.trace-section {{ border-top: 1px solid #d0d7de; max-height: 260px; overflow-y: auto; flex-shrink: 0; }}
.trace-section summary {{ padding: 8px 14px; font-size: 12px; font-weight: 600; color: #656d76; cursor: pointer; background: #f6f8fa; user-select: none; }}
.trace-table {{ width: 100%; border-collapse: collapse; font-size: 12px; }}
.trace-table th, .trace-table td {{ padding: 3px 10px; text-align: left; border-bottom: 1px solid #d0d7de; color: #1f2328; }}
.trace-table th {{ background: #f6f8fa; font-weight: 600; color: #656d76; position: sticky; top: 0; }}
.trace-table .ch-swatch {{ display: inline-block; width: 10px; height: 10px; border-radius: 2px; margin-right: 4px; vertical-align: middle; }}

/* ── View containers ──────────────────────────────────── */
#view-sequence {{ display: flex; flex-direction: column; flex: 1; overflow: hidden; }}

/* ── Live server status ───────────────────────────────── */
.server-status {{ display: flex; align-items: center; gap: 8px; font-size: 12px; }}
.status-dot {{ width: 10px; height: 10px; border-radius: 50%; background: #ef4444; transition: background 0.3s; flex-shrink: 0; }}
.status-dot.live {{ background: #22c55e; }}
.status-dot.checking {{ background: #f59e0b; animation: pulse 1s infinite; }}
@keyframes pulse {{ 50% {{ opacity: 0.4; }} }}
.server-input {{ width: 100%; padding: 5px 8px; border-radius: 4px; border: 1px solid #334155; background: #0f172a; color: #e2e8f0; font-size: 11px; font-family: monospace; outline: none; }}
.server-input:focus {{ border-color: #3b82f6; }}

/* ── Spinner overlay ──────────────────────────────────── */
.spinner-overlay {{ position: absolute; inset: 0; background: rgba(255,255,255,0.85); display: none; align-items: center; justify-content: center; z-index: 50; }}
.spinner-overlay.active {{ display: flex; }}
.spinner {{ width: 32px; height: 32px; border: 3px solid #d0d7de; border-top-color: #3b82f6; border-radius: 50%; animation: spin 0.6s linear infinite; }}
@keyframes spin {{ to {{ transform: rotate(360deg); }} }}
.live-elapsed {{ font-size: 10px; color: #94a3b8; margin-top: 4px; }}

/* ── Setup instructions ────────────────────────────────── */
.setup-toggle {{ font-size: 12px; cursor: pointer; color: #94a3b8; user-select: none; }}
.setup-toggle:hover {{ color: #e2e8f0; }}
.setup-content {{ font-size: 12px; line-height: 1.6; color: #94a3b8; }}
.setup-content code {{ background: #0f172a; padding: 2px 6px; border-radius: 4px; font-size: 11px; color: #a5f3fc; word-break: break-all; }}
.setup-content ol {{ padding-left: 18px; }}

/* ── Editor pane (left column in split view) ───────────── */
.editor-pane {{ display: none; flex-direction: column; flex: 2; min-width: 350px; border-right: 2px solid #30363d; background: #0d1117; overflow: hidden; }}
.editor-pane.active {{ display: flex; }}
.editor-header {{ display: flex; align-items: center; justify-content: space-between; padding: 8px 14px; background: #161b22; border-bottom: 1px solid #30363d; min-height: 40px; flex-shrink: 0; }}
.editor-header span {{ font-size: 13px; font-weight: 600; color: #c9d1d9; }}
.btn-run-tlc {{ display: inline-flex; align-items: center; gap: 6px; padding: 6px 16px; border-radius: 6px; border: none; font-size: 13px; font-weight: 600; cursor: pointer; background: #059669; color: #fff; transition: background 0.15s; }}
.btn-run-tlc:hover:not(:disabled) {{ background: #047857; }}
.btn-run-tlc:disabled {{ opacity: 0.5; cursor: not-allowed; }}
.btn-run-tlc .spinner-sm {{ display: none; width: 14px; height: 14px; border: 2px solid rgba(255,255,255,0.3); border-top-color: #fff; border-radius: 50%; animation: spin 0.6s linear infinite; }}
.btn-run-tlc.running .spinner-sm {{ display: inline-block; }}
.btn-run-tlc.running .run-icon {{ display: none; }}
.btn-save-pcal {{ display: inline-flex; align-items: center; gap: 5px; padding: 6px 12px; border-radius: 6px; border: 1px solid #30363d; font-size: 13px; cursor: pointer; background: #21262d; color: #c9d1d9; transition: background 0.15s; }}
.btn-save-pcal:hover {{ background: #30363d; }}
.editor-status {{ font-size: 12px; color: #8b949e; }}
.editor-status.error {{ color: #f85149; }}
.editor-status.success {{ color: #3fb950; }}

/* ── Monaco container ──────────────────────────────────── */
.monaco-container {{ flex: 1; overflow: hidden; border-bottom: 1px solid #30363d; min-height: 200px; }}

/* ── Error panel ───────────────────────────────────────── */
.error-panel {{ display: none; max-height: 200px; overflow-y: auto; padding: 10px 14px; background: #2d1117; border-top: 2px solid #f85149; flex-shrink: 0; }}
.error-panel.active {{ display: block; }}
.error-panel-header {{ display: flex; align-items: center; justify-content: space-between; margin-bottom: 6px; }}
.error-panel-header span {{ font-size: 12px; font-weight: 600; color: #f85149; }}
.error-panel-header button {{ background: none; border: none; color: #f85149; cursor: pointer; font-size: 14px; padding: 2px 6px; }}
.error-panel pre {{ font-family: "Cascadia Code", "Fira Code", "Consolas", monospace; font-size: 11px; color: #ffa198; white-space: pre-wrap; word-break: break-word; margin: 0; line-height: 1.5; }}

/* ── SVG lifeline enhancement ──────────────────────────── */
.lifelines line {{ stroke: #999999 !important; stroke-width: 2px !important; }}
</style>
</head>
<body>

<!-- ── Top bar ──────────────────────────────────────────── -->
<div class="topbar">
  <h1>{title}</h1>
  <div class="topbar-right">
    <span class="flow-count" id="flow-count"></span>
    <span class="badge badge-static" id="mode-badge">STATIC</span>
  </div>
</div>

<!-- ── Main layout ──────────────────────────────────────── -->
<div class="main-layout">

  <!-- ── Sidebar ──────────────────────────────────────── -->
  <div class="sidebar">
    <div>
      <h2>Flow Selection</h2>
{dropdowns_html}
    </div>

    <hr>

    <div id="legend-section"{" style=\"display:none\"" if not has_channels else ""}>
      <h2>Channel Legend</h2>
      <div class="legend" id="legend"></div>
    </div>
    {'<hr>' if has_channels else ''}

    <div>
      <h2>PlantUML Server</h2>
      <div class="server-status">
        <div class="status-dot" id="puml-status-dot"></div>
        <span id="puml-status-text">Not connected</span>
      </div>
      <div style="height:6px"></div>
      <input class="server-input" id="inp-puml-server" value="{plantuml_server}" placeholder="https://plantuml.example.com/uml">
      <button class="btn btn-secondary" id="btn-puml-connect" style="margin-top:6px;font-size:12px">Connect</button>
      <div style="font-size:11px;color:#94a3b8;margin-top:4px">Renders sequence diagrams from embedded PlantUML source. Without a server, raw PlantUML text is shown.</div>
    </div>

    <hr>
    <div>
      <h2>TLC Server</h2>
      <div class="server-status">
        <div class="status-dot" id="status-dot"></div>
        <span id="status-text">Not connected</span>
      </div>
      <div style="height:6px"></div>
      <input class="server-input" id="inp-server" value="{tlc_server}" placeholder="http://host:port">
      <button class="btn btn-secondary" id="btn-connect" style="margin-top:6px;font-size:12px">Connect</button>
      <div class="live-elapsed" id="live-elapsed"></div>
      <div style="margin-top:10px">
        <span class="setup-toggle" id="setup-toggle">&#9654; Setup Instructions</span>
        <div id="setup-content" class="setup-content" style="display:none; margin-top:8px;">
          <ol>
            <li>Ensure <code>java</code> (JDK&nbsp;17+) and <code>python</code> (3.10+) are on your PATH</li>
            <li>Download <a href="server.zip" style="color:#7dd3fc" download><strong>server.zip</strong></a> and extract to a local folder</li>
            <li>Run:<br><code>python tlc_server.py</code></li>
            <li>Enter <code>http://127.0.0.1:18080</code> above and click <strong>Connect</strong></li>
          </ol>
          <p style="margin-top:6px">The server runs TLC model-checking on demand. Parameter changes and <b>Run&nbsp;TLC</b> will POST to the server and re-render live traces.</p>
          <p style="margin-top:4px;font-size:11px">Optional flags:<br>
            <code>--port 18082</code> &mdash; custom port<br>
            <code>--host 0.0.0.0</code> &mdash; bind all interfaces
          </p>
        </div>
      </div>
    </div>

    <hr>
    <div style="font-size:11px; color:#64748b; margin-top:auto;">
      <a href="DOCUMENTATION.html" style="color:#7dd3fc; text-decoration:none;">&#128196; Documentation</a><br>
      {_render_footer_links(branding)}
      <span style="font-size:10px">TLC-verified &middot; {len(all_traces)} flows</span>
      {_render_branding_footer(branding)}
    </div>
  </div>

  <!-- ── Content area (editor + diagram side by side) ──── -->
  <div class="content-area" id="content-area">

    <!-- ── Left: PlusCal editor pane ───────────────────── -->
    <div class="editor-pane" id="editor-pane">
      <div class="editor-header">
        <span>PlusCal Editor</span>
        <div style="display:flex; align-items:center; gap:8px;">
          <button class="btn-save-pcal" id="btn-save-pcal" title="Download editor content as .pcal file">&#128190; Save</button>
          <button class="btn-run-tlc" id="btn-run-tlc" disabled title="Start python tlc_server.py to enable">
            <span class="run-icon">&#9654;</span>
            <span class="spinner-sm"></span>
            Run TLC
          </button>
          <span class="editor-status" id="editor-status"></span>
        </div>
      </div>
      <div class="monaco-container" id="monaco-container"></div>
      <div class="error-panel" id="error-panel">
        <div class="error-panel-header">
          <span>&#9888; Error</span>
          <button id="btn-close-error" title="Close">&times;</button>
        </div>
        <pre id="error-output"></pre>
      </div>
    </div>

    <!-- ── Right: diagram pane ────────────────────────── -->
    <div class="diagram-pane" id="diagram-pane">
      <div class="diagram-header">
        <span id="diagram-title" style="flex:1;">Select a flow</span>
        <div class="diagram-toolbar">
          <button class="btn btn-sm btn-secondary" id="btn-copy-puml" title="Copy PlantUML text to clipboard" style="display:none">&#128203; Copy PlantUML</button>
          <button class="btn btn-sm btn-secondary" id="btn-export" title="Download SVG" style="display:none">&#11015; SVG</button>
        </div>
      </div>

      <!-- ── Sequence view ─────────────────────────────── -->
      <div id="view-sequence">
        <!-- Single diagram view -->
        <div class="diagram-container main-view" id="diagram-container">
          <p class="no-diagram">Select a flow from the sidebar.</p>
          <div class="spinner-overlay" id="spinner"><div class="spinner"></div></div>
        </div>

        <!-- Trace table (collapsible, populated in live mode) -->
        <details class="trace-section" id="trace-section" style="display:none">
          <summary>Message Trace</summary>
          <table class="trace-table" id="trace-table">
            <thead><tr><th>#</th><th>Src</th><th>&rarr;</th><th>Dst</th><th>Message</th><th>Channel</th></tr></thead>
            <tbody></tbody>
          </table>
        </details>

      </div>

    </div>

  </div>
</div>

<!-- ── Embedded data ────────────────────────────────────── -->
<script>
const ALL_TRACES  = {json.dumps(all_traces, separators=(",", ":"))};
const FLOW_TREE   = {json.dumps(flow_tree, separators=(",", ":"))};
const CONSTANT_NAMES = {json.dumps(constant_names)};
const PCAL_SOURCE = {json.dumps(pcal_source)};
const PLANTUML_SERVER = {json.dumps(plantuml_server or "")};
const CHANNEL_STYLES = {json.dumps(channel_styles, separators=(",", ":"))};
const PARTICIPANTS = {json.dumps(participants)};
const INVALID_COMBOS = new Set({json.dumps(invalid_combos)});
const SKIPPED_COMBOS = new Set({json.dumps(skipped_combos)});</script>

<!-- ── Application logic ────────────────────────────────── -->
<script>
(function() {{
  "use strict";

  /* ── DOM references ─────────────────────────────────── */
  const selectors   = CONSTANT_NAMES.map((_, i) => document.getElementById("sel-const-" + i));
  const container   = document.getElementById("diagram-container");
  const diagramPane = document.getElementById("diagram-pane");
  const titleEl     = document.getElementById("diagram-title");
  const tbody       = document.querySelector("#trace-table tbody");
  const btnExport   = document.getElementById("btn-export");
  const btnCopyPuml = document.getElementById("btn-copy-puml");
  const legendEl    = document.getElementById("legend");
  const legendSection = document.getElementById("legend-section");
  const flowCountEl = document.getElementById("flow-count");

  const statusDot  = document.getElementById("status-dot");
  const statusText  = document.getElementById("status-text");
  const inpServer   = document.getElementById("inp-server");
  const btnConnect  = document.getElementById("btn-connect");
  const modeBadge   = document.getElementById("mode-badge");
  const spinnerEl   = document.getElementById("spinner");
  const elapsedEl   = document.getElementById("live-elapsed");
  const inpPumlServer = document.getElementById("inp-puml-server");
  const btnPumlConnect = document.getElementById("btn-puml-connect");
  const pumlStatusDot = document.getElementById("puml-status-dot");
  const pumlStatusText = document.getElementById("puml-status-text");

  let currentKey = null;
  let lastTraceData = null;  // most recently rendered trace (static, live, or custom)
  let liveMode = false;
  const CUSTOM_TRACES = {{}};  // cache for custom TLC runs (keyed by combo key)
  let heartbeatTimer = null;
  let pumlServerLive = false;   // whether PlantUML server health-check passed
  let serverUrl = inpServer.value.replace(/\\/+$/, "");

  /* ── PlantUML server connect / disconnect ─────────── */
  function getPumlServerUrl() {{
    return (inpPumlServer.value || "").replace(/\\/+$/, "");
  }}

  function connectPumlServer() {{
    const url = getPumlServerUrl();
    if (!url) {{ disconnectPumlServer(); return; }}
    pumlStatusDot.className = "status-dot checking";
    pumlStatusText.textContent = "Checking\u2026";
    btnPumlConnect.disabled = true;

    // PlantUML servers don't have /api/health — probe with a known-good encoded diagram
    // "Bob -> Alice : ok" encoded with standard PlantUML encoding (deflate-raw + custom base64, no prefix)
    const testUrl = url + "/svg/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000";
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 5000);

    fetch(testUrl, {{ signal: controller.signal, mode: "cors" }})
      .then(r => {{
        clearTimeout(timeout);
        if (!r.ok) throw new Error("HTTP " + r.status);
        return r.text();
      }})
      .then(svg => {{
        // Verify it rendered our test diagram (contains "Alice"), not the default
        if (svg.includes("Alice")) {{
          setPumlConnected();
        }} else {{
          throw new Error("Server returned default diagram — encoding may not be supported");
        }}
      }})
      .catch(() => {{
        clearTimeout(timeout);
        disconnectPumlServer();
        pumlStatusText.textContent = "Failed to connect";
      }})
      .finally(() => {{ btnPumlConnect.disabled = false; }});
  }}

  function setPumlConnected() {{
    pumlServerLive = true;
    pumlStatusDot.className = "status-dot live";
    pumlStatusText.textContent = "Connected";
    btnPumlConnect.textContent = "Disconnect";
    btnPumlConnect.style.background = "#7f1d1d";
    btnPumlConnect.style.color = "#fca5a5";
    inpPumlServer.disabled = true;
    if (lastTraceData) refreshDiagram(lastTraceData);
  }}

  function disconnectPumlServer() {{
    pumlServerLive = false;
    pumlStatusDot.className = "status-dot";
    pumlStatusText.textContent = "Not connected";
    btnPumlConnect.textContent = "Connect";
    btnPumlConnect.style.background = "";
    btnPumlConnect.style.color = "";
    inpPumlServer.disabled = false;
    btnExport.style.display = "none";
    if (lastTraceData) refreshDiagram(lastTraceData);
  }}

  function togglePumlConnection() {{
    if (pumlServerLive) disconnectPumlServer();
    else connectPumlServer();
  }}

  btnPumlConnect.addEventListener("click", togglePumlConnection);
  inpPumlServer.addEventListener("keydown", (e) => {{ if (e.key === "Enter") connectPumlServer(); }});

  const nTraces = Object.keys(ALL_TRACES).length;
  const nInvalid = INVALID_COMBOS.size;
  const nSkipped = SKIPPED_COMBOS.size;
  const nTotal = nTraces + nInvalid + nSkipped;
  flowCountEl.textContent = nTraces + " / " + nTotal + " flows";

  /* ── Humanize helper ────────────────────────────────── */
  function humanize(s) {{
    return s.replace(/_/g, " ").replace(/\\b\\w/g, c => c.toUpperCase())
            .replace(/\\bIo\\$/g, "IO$").replace(/\\bIo\\b/g, "IO")
            .replace(/\\bCa\\b/g, "CA").replace(/\\bHa\\b/g, "HA")
            .replace(/\\bPcie\\b/g, "PCIe");
  }}

  /* ── Build legend (config CHANNEL_STYLES, overlaid by live data) ── */
  function buildLegend(data) {{
    legendEl.innerHTML = "";
    const styles = CHANNEL_STYLES;
    const seenCh = new Map();
    Object.values(styles).forEach(v => {{
      if (!seenCh.has(v.name)) seenCh.set(v.name, v.stroke);
    }});
    if (seenCh.size > 0 && legendSection) legendSection.style.display = "";
    seenCh.forEach((color, name) => {{
      const s = document.createElement("span");
      s.className = "legend-item";
      s.innerHTML = '<span class="legend-swatch" style="background:' + color + '"></span>' + name;
      legendEl.appendChild(s);
    }});
  }}

  /* ── Generic cascading dropdowns ─────────────────────── */
  function getNodeAtLevel(level) {{
    // Walk FLOW_TREE using selected values for levels 0..level-1
    let node = FLOW_TREE;
    for (let i = 0; i < level; i++) {{
      if (!node || typeof node !== "object" || Array.isArray(node)) return {{}};
      node = node[selectors[i].value];
    }}
    return node || {{}};
  }}

  function populateLevel(level) {{
    const sel = selectors[level];
    const prev = sel.value;
    sel.innerHTML = "";
    const node = getNodeAtLevel(level);
    const isLast = (level === CONSTANT_NAMES.length - 1);
    const keys = isLast && Array.isArray(node) ? node : Object.keys(node);
    for (const k of keys) {{
      const o = document.createElement("option");
      o.value = k; o.textContent = humanize(String(k));
      sel.appendChild(o);
    }}
    if (prev && [...sel.options].some(o => o.value === prev)) sel.value = prev;
    if (level + 1 < CONSTANT_NAMES.length) {{
      populateLevel(level + 1);
    }} else {{
      onFlowChange();
    }}
  }}

  // Wire change events
  selectors.forEach((sel, i) => {{
    sel.addEventListener("change", () => {{
      if (i + 1 < CONSTANT_NAMES.length) populateLevel(i + 1);
      else onFlowChange();
    }});
  }});

  /* ── Flow change handler ────────────────────────────── */
  function onFlowChange() {{
    const vals = selectors.map(s => s.value);
    if (vals.some(v => !v)) return;

    currentKey = vals.join(".");
    titleEl.textContent = vals.map(humanize).join(" \\u203A ");

    // Invalid combo check (applies in both static and live modes)
    if (INVALID_COMBOS.has(currentKey)) {{
      container.innerHTML = '<div class="combo-status combo-invalid">'
        + '<span class="combo-status-icon">&#9888;</span>'
        + '<p><b>Invalid combination</b></p>'
        + '<p>This parameter combination is not physically possible.</p></div>';
      btnExport.style.display = "none";
      btnCopyPuml.style.display = "none";
      elapsedEl.textContent = "";
      clearTraceTable();
      updateUrl();
      return;
    }}

    // Try cached custom trace first (from a previous "Run TLC" click)
    if (CUSTOM_TRACES[currentKey]) {{
      renderTraceData(CUSTOM_TRACES[currentKey]);
      elapsedEl.textContent = "Custom (cached)";
      updateUrl();
      return;
    }}

    // Try pre-computed sweep data
    const data = ALL_TRACES[currentKey];
    if (data) {{
      renderTraceData(data);
      elapsedEl.textContent = "";
      updateUrl();
      return;
    }}

    // Skipped / not-yet-explored combo
    if (SKIPPED_COMBOS.has(currentKey)) {{
      const hint = liveMode
        ? 'Click <b>Run TLC</b> to generate its trace.'
        : 'Connect in <b>Live</b> mode or run a full sweep to obtain its trace.';
      container.innerHTML = '<div class="combo-status combo-skipped">'
        + '<span class="combo-status-icon">&#9203;</span>'
        + '<p><b>Combination not yet explored</b></p>'
        + '<p>This valid combination was skipped during the sweep.<br>' + hint + '</p></div>';
      btnExport.style.display = "none";
      btnCopyPuml.style.display = "none";
      elapsedEl.textContent = "";
      clearTraceTable();
      updateUrl();
      return;
    }}

    // Truly unknown combo
    container.innerHTML = '<p class="no-diagram">Trace not found for ' + currentKey + '</p>';
    elapsedEl.textContent = "";
    clearTraceTable();
    updateUrl();
  }}

  /* ── Clear trace table ─────────────────────────────── */
  function clearTraceTable() {{
    const traceSection = document.getElementById("trace-section");
    tbody.innerHTML = "";
    traceSection.style.display = "none";
  }}

  /* ── Parse trace from PlantUML text ─────────────────── */
  function parseTraceFromPuml(pumlText) {{
    if (!pumlText) return [];
    // Build alias → display-name map from participant declarations
    const aliasMap = {{}};
    const partRe = /^participant\\s+"([^"]+)"\\s+as\\s+(\\S+)/gm;
    let pm;
    while ((pm = partRe.exec(pumlText)) !== null) {{
      aliasMap[pm[2]] = pm[1];
    }}
    // Match arrow lines:
    //   Src -[#color]> Dst : <color:#hex><b>MSG</b></color>\\n<color:#hex><size:9>CH</size></color>
    const arrowRe = /^\\s*(\\S+)\\s+-\\[#[0-9a-fA-F]+(?:,\\w+)?\\]>\\s+(\\S+)\\s+:\\s+<color:#[0-9a-fA-F]+><b>(.+?)<\\/b><\\/color>(?:\\\\n<color:#[0-9a-fA-F]+><size:9>(.+?)<\\/size><\\/color>)?/gm;
    const trace = [];
    let am;
    while ((am = arrowRe.exec(pumlText)) !== null) {{
      trace.push({{
        src: aliasMap[am[1]] || am[1],
        dst: aliasMap[am[2]] || am[2],
        msg: am[3],
        ch:  am[4] || ""
      }});
    }}
    return trace;
  }}

  /* ── Render trace data (shared by static & live) ────── */
  function renderTraceData(data) {{
    lastTraceData = data;
    buildLegend(data);
    refreshDiagram(data);

    // Parse trace from PlantUML text (works for sweep, custom, and live data)
    const traceSection = document.getElementById("trace-section");
    tbody.innerHTML = "";
    const trace = parseTraceFromPuml(data && data.puml_text);
    if (trace.length > 0) {{
      traceSection.style.display = "";
      const styles = Object.assign({{}}, CHANNEL_STYLES);
      trace.forEach((m, i) => {{
        const chKey = m.ch || "";
        const ch = (chKey && styles[chKey]) || {{ stroke: "#616161", name: chKey || "—" }};
        const tr = document.createElement("tr");
        tr.innerHTML = "<td>" + (i+1) + "</td>"
          + "<td>" + m.src + "</td><td>\\u2192</td><td>" + m.dst + "</td>"
          + "<td><b>" + m.msg + "</b></td>"
          + '<td><span class="ch-swatch" style="background:' + ch.stroke + '"></span>' + ch.name + "</td>";
        tbody.appendChild(tr);
      }});
    }} else {{
      traceSection.style.display = "none";
    }}
  }}

  /* ── PlantUML text encoding (deflate-raw + custom base64) ── */
  const PUML_B64 = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-_";
  function pumlEncode6bit(b) {{ return PUML_B64.charAt(b & 0x3f); }}
  function pumlEncode3bytes(b1, b2, b3) {{
    let r = "";
    r += pumlEncode6bit(b1 >> 2);
    r += pumlEncode6bit(((b1 & 0x3) << 4) | (b2 >> 4));
    r += pumlEncode6bit(((b2 & 0xf) << 2) | (b3 >> 6));
    r += pumlEncode6bit(b3);
    return r;
  }}
  function pumlEncodeBytes(data) {{
    let r = "";
    for (let i = 0; i < data.length; i += 3) {{
      const b1 = data[i];
      const b2 = (i + 1 < data.length) ? data[i + 1] : 0;
      const b3 = (i + 2 < data.length) ? data[i + 2] : 0;
      r += pumlEncode3bytes(b1, b2, b3);
    }}
    return r;
  }}

  async function encodePlantUml(text) {{
    const utf8 = new TextEncoder().encode(text);
    let deflated;
    try {{
      // Preferred: raw deflate (no zlib wrapper)
      const cs = new CompressionStream("deflate-raw");
      const writer = cs.writable.getWriter();
      writer.write(utf8);
      writer.close();
      const chunks = [];
      const reader = cs.readable.getReader();
      while (true) {{
        const {{ done, value }} = await reader.read();
        if (done) break;
        chunks.push(value);
      }}
      const totalLen = chunks.reduce((s, c) => s + c.length, 0);
      deflated = new Uint8Array(totalLen);
      let off = 0;
      for (const c of chunks) {{ deflated.set(c, off); off += c.length; }}
    }} catch (_e) {{
      // Fallback: zlib deflate, strip 2-byte header + 4-byte adler32 to get raw deflate
      const cs = new CompressionStream("deflate");
      const writer = cs.writable.getWriter();
      writer.write(utf8);
      writer.close();
      const chunks = [];
      const reader = cs.readable.getReader();
      while (true) {{
        const {{ done, value }} = await reader.read();
        if (done) break;
        chunks.push(value);
      }}
      const totalLen = chunks.reduce((s, c) => s + c.length, 0);
      const full = new Uint8Array(totalLen);
      let off = 0;
      for (const c of chunks) {{ full.set(c, off); off += c.length; }}
      deflated = full.subarray(2, full.length - 4);
    }}
    // Standard PlantUML encoding: no prefix
    return pumlEncodeBytes(deflated);
  }}

  /* ── Diagram rendering (PlantUML server or raw text) ── */
  function showPumlCode(text) {{
    const pre = document.createElement("pre");
    pre.style.cssText = "padding:16px; background:#1e293b; color:#e2e8f0; border-radius:6px; overflow:auto; font-size:13px; line-height:1.5;";
    pre.textContent = text;
    container.appendChild(pre);
  }}

  async function refreshDiagram(data) {{
    container.innerHTML = "";
    btnExport.style.display = "none";
    if (!data) {{ btnCopyPuml.style.display = "none"; return; }}

    // Show/hide Copy PlantUML button based on availability
    btnCopyPuml.style.display = data.puml_text ? "" : "none";

    if (data.puml_text && pumlServerLive) {{
      // PlantUML server connected: fetch SVG via fetch()
      try {{
        const encoded = await encodePlantUml(data.puml_text);
        const url = getPumlServerUrl() + "/svg/" + encoded;
        const resp = await fetch(url, {{ mode: "cors" }});
        if (!resp.ok) throw new Error("HTTP " + resp.status);
        const svg = await resp.text();
        container.innerHTML = svg;
        btnExport.style.display = "";
      }} catch (e) {{
        // Fallback to raw text on fetch failure
        showPumlCode(data.puml_text);
      }}
    }} else if (data.puml_text) {{
      // No server connected: show raw PlantUML text
      showPumlCode(data.puml_text);
    }} else {{
      container.innerHTML = '<p class="no-diagram">No diagram data available.</p>';
    }}
  }}

  /* ── URL parameters ─────────────────────────────────── */
  function updateUrl() {{
    const url = new URL(window.location);
    CONSTANT_NAMES.forEach((name, i) => {{
      url.searchParams.set(name, selectors[i].value);
    }});
    history.replaceState(null, "", url);
  }}

  function loadFromUrl() {{
    const p = new URLSearchParams(window.location.search);
    let anyFound = false;
    CONSTANT_NAMES.forEach((name, i) => {{
      const val = p.get(name);
      if (val) {{
        anyFound = true;
        selectors[i].value = val;
        if (i + 1 < CONSTANT_NAMES.length) populateLevel(i + 1);
      }}
    }});
    if (anyFound) onFlowChange();
  }}

  /* ── Copy PlantUML ──────────────────────────────────── */
  btnCopyPuml.addEventListener("click", () => {{
    if (lastTraceData && lastTraceData.puml_text) {{
      navigator.clipboard.writeText(lastTraceData.puml_text).then(() => {{
        const orig = btnCopyPuml.textContent;
        btnCopyPuml.textContent = "\u2713 Copied!";
        setTimeout(() => {{ btnCopyPuml.textContent = orig; }}, 1500);
      }});
    }}
  }});

  /* ── Export SVG ─────────────────────────────────────── */
  btnExport.addEventListener("click", () => {{
    const filename = (currentKey || "diagram").replace(/\\./g, "_");
    const svgEl = container.querySelector("svg");
    if (!svgEl) {{ alert("No diagram to export."); return; }}
    const svgData = new XMLSerializer().serializeToString(svgEl);
    const blob = new Blob([svgData], {{ type: "image/svg+xml" }});
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a"); a.href = url; a.download = filename + ".svg";
    document.body.appendChild(a); a.click(); document.body.removeChild(a); URL.revokeObjectURL(url);
  }});

  /* ── Server connect / disconnect ─────────────────────── */
  function toggleConnection() {{
    if (liveMode) {{
      setStatic();
      return;
    }}
    serverUrl = inpServer.value.replace(/\\/+$/, "");
    statusDot.className = "status-dot checking";
    statusText.textContent = "Checking\u2026";
    btnConnect.disabled = true;

    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 3000);

    fetch(serverUrl + "/api/health", {{ signal: controller.signal }})
      .then(r => {{
        if (!r.ok) throw new Error("HTTP " + r.status);
        return r.json();
      }})
      .then(d => {{
        clearTimeout(timeout);
        btnConnect.disabled = false;
        if (d.status === "ok" && d.model) {{
          setLive(d);
        }} else {{
          statusText.textContent = "Not a TLC server";
          setStatic();
        }}
      }})
      .catch(() => {{
        clearTimeout(timeout);
        btnConnect.disabled = false;
        setStatic();
      }});
  }}

  function setLive(health) {{
    liveMode = true;
    statusDot.className = "status-dot live";
    statusText.textContent = "Connected";
    modeBadge.className = "badge badge-live";
    modeBadge.textContent = "LIVE";
    btnConnect.textContent = "Disconnect";
    btnConnect.style.background = "#7f1d1d";
    btnConnect.style.color = "#fca5a5";
    inpServer.disabled = true;
    updateEditorPaneState();
    // Start heartbeat — auto-disconnect if server goes away
    if (heartbeatTimer) clearInterval(heartbeatTimer);
    heartbeatTimer = setInterval(checkHeartbeat, 15000);
    // Re-render current flow via server
    if (currentKey) onFlowChange();
  }}

  function setStatic() {{
    liveMode = false;
    if (heartbeatTimer) {{ clearInterval(heartbeatTimer); heartbeatTimer = null; }}
    statusDot.className = "status-dot";
    statusText.textContent = "Not connected";
    modeBadge.className = "badge badge-static";
    modeBadge.textContent = "STATIC";
    elapsedEl.textContent = "";
    btnConnect.textContent = "Connect";
    btnConnect.style.background = "";
    btnConnect.style.color = "";
    inpServer.disabled = false;
    updateEditorPaneState();
    // Re-render from embedded data
    if (currentKey) onFlowChange();
  }}

  function checkHeartbeat() {{
    const c = new AbortController();
    const t = setTimeout(() => c.abort(), 3000);
    fetch(serverUrl + "/api/health", {{ signal: c.signal }})
      .then(r => {{ clearTimeout(t); if (!r.ok) throw 0; return r.json(); }})
      .then(d => {{ if (d.status !== "ok") setStatic(); }})
      .catch(() => {{ clearTimeout(t); setStatic(); }});
  }}

  /* ── Event wiring ───────────────────────────────────── */
  btnConnect.addEventListener("click", toggleConnection);
  inpServer.addEventListener("keydown", (e) => {{ if (e.key === "Enter") toggleConnection(); }});

  document.getElementById("setup-toggle").addEventListener("click", () => {{
    const el = document.getElementById("setup-content");
    const toggle = document.getElementById("setup-toggle");
    if (el.style.display === "none") {{
      el.style.display = "block"; toggle.innerHTML = "&#9660; Setup Instructions";
    }} else {{
      el.style.display = "none"; toggle.innerHTML = "&#9654; Setup Instructions";
    }}
  }});

  /* ── Editor pane management ─────────────────────────── */
  const editorPane   = document.getElementById("editor-pane");
  const btnRunTlc    = document.getElementById("btn-run-tlc");
  const btnSavePcal  = document.getElementById("btn-save-pcal");
  const editorStatusEl = document.getElementById("editor-status");
  const monacoContainer = document.getElementById("monaco-container");
  const errorPanel   = document.getElementById("error-panel");
  const errorOutput  = document.getElementById("error-output");
  const btnCloseErr  = document.getElementById("btn-close-error");

  let monacoEditor = null;
  let monacoLoaded = false;

  /* ── Show/hide editor pane based on live mode ───────── */
  function updateEditorPaneState() {{
    // Editor pane always visible (PlusCal source is useful in static mode too)
    editorPane.classList.add("active");
    // Lazy-load Monaco on first show
    if (!monacoLoaded) {{
      monacoLoaded = true;
      loadMonaco();
    }} else if (monacoEditor) {{
      monacoEditor.layout();
    }}
    if (liveMode) {{
      btnRunTlc.style.display = "";
      btnRunTlc.disabled = false;
      btnRunTlc.title = "Run TLC with the current editor source";
    }} else {{
      btnRunTlc.style.display = "none";
    }}
  }}

  /* ── Monaco loader from CDN ─────────────────────────── */
  function loadMonaco() {{
    editorStatusEl.textContent = "Loading editor\\u2026";
    editorStatusEl.className = "editor-status";

    const loaderScript = document.createElement("script");
    loaderScript.src = "https://cdn.jsdelivr.net/npm/monaco-editor@0.45.0/min/vs/loader.js";
    loaderScript.onload = () => {{
      require.config({{
        paths: {{ vs: "https://cdn.jsdelivr.net/npm/monaco-editor@0.45.0/min/vs" }}
      }});
      require(["vs/editor/editor.main"], () => {{
        initMonaco();
      }});
    }};
    loaderScript.onerror = () => {{
      editorStatusEl.textContent = "Failed to load Monaco editor from CDN";
      editorStatusEl.className = "editor-status error";
    }};
    document.head.appendChild(loaderScript);
  }}

  /* ── TLA+ Monarch tokenizer ─────────────────────────── */
  function initMonaco() {{
    // Register TLA+ language
    monaco.languages.register({{ id: "tlaplus" }});

    // Monarch tokenizer for TLA+/PlusCal
    monaco.languages.setMonarchTokensProvider("tlaplus", {{
      keywords: [
        "MODULE", "EXTENDS", "CONSTANTS", "CONSTANT", "VARIABLES", "VARIABLE",
        "ASSUME", "AXIOM", "THEOREM", "LEMMA", "PROPOSITION",
        "INSTANCE", "LOCAL", "LET", "IN", "IF", "THEN", "ELSE",
        "CASE", "OTHER", "CHOOSE", "WITH", "EXCEPT",
        "DOMAIN", "SUBSET", "UNION", "ENABLED", "UNCHANGED",
        "SPECIFICATION", "INVARIANT", "PROPERTY",
        "TRUE", "FALSE", "BOOLEAN", "STRING",
        "assert", "print",
      ],
      pcalKeywords: [
        "algorithm", "variables", "variable", "define", "macro", "procedure",
        "process", "fair", "begin", "end", "if", "then", "else", "elsif",
        "while", "do", "either", "or", "with", "await", "when",
        "skip", "call", "return", "goto", "assert", "print",
      ],
      operators: [
        "==", "/=", ">=", "<=", "=>", "->", "<-", "|->",
        ":=", "::=", "=", "#", "<", ">",
        "+", "-", "*", "/", "%", "^",
        "~", "@@",
      ],
      symbols: /[=><!~?:&|+\\-*\\/\\^%#@]+/,

      tokenizer: {{
        root: [
          // Line comments: \\*
          [/\\\\\\*.*$/, "comment"],

          // Block comments: (* ... *)
          [/\\(\\*/, "comment", "@blockComment"],

          // PlusCal block markers
          [/(--algorithm|--fair\\s+algorithm)/, "keyword.pcal"],
          [/\\(\\*\\s*--algorithm/, "keyword.pcal"],

          // Strings
          [/"[^"]*"/, "string"],

          // Numbers
          [/\\d+/, "number"],

          // Module delimiters
          [/----+/, "delimiter"],
          [/====+/, "delimiter"],

          // Identifiers and keywords
          [/[a-zA-Z_][a-zA-Z0-9_]*/, {{
            cases: {{
              "@keywords": "keyword",
              "@pcalKeywords": "keyword.pcal",
              "@default": "identifier"
            }}
          }}],

          // TLA+ set operators
          [/\\\\in\\b/, "keyword.operator"],
          [/\\\\notin\\b/, "keyword.operator"],
          [/\\\\cup\\b/, "keyword.operator"],
          [/\\\\cap\\b/, "keyword.operator"],
          [/\\\\subseteq\\b/, "keyword.operator"],
          [/\\\\union\\b/, "keyword.operator"],
          [/\\\\subset\\b/, "keyword.operator"],
          [/\\\\\\//, "keyword.operator"],
          [/\\/\\\\/, "keyword.operator"],

          // Operators
          [/@symbols/, {{
            cases: {{
              "@operators": "operator",
              "@default": ""
            }}
          }}],

          // Brackets
          [/[{{}}()\\[\\]]/, "delimiter.bracket"],
          [/<</, "delimiter.angle"],
          [/>>/, "delimiter.angle"],
        ],

        blockComment: [
          [/[^*(]+/, "comment"],
          [/\\*\\)/, "comment", "@pop"],
          [/[*(]/, "comment"],
        ],
      }}
    }});

    // Create the editor
    monacoEditor = monaco.editor.create(monacoContainer, {{
      value: PCAL_SOURCE,
      language: "tlaplus",
      theme: "vs-dark",
      fontSize: 13,
      fontFamily: "'Cascadia Code', 'Fira Code', 'Consolas', monospace",
      minimap: {{ enabled: true, maxColumn: 80 }},
      scrollBeyondLastLine: false,
      automaticLayout: true,
      wordWrap: "off",
      lineNumbers: "on",
      renderLineHighlight: "line",
      tabSize: 2,
      readOnly: false,
    }});

    editorStatusEl.textContent = "Ready";
    editorStatusEl.className = "editor-status success";
    setTimeout(() => {{ editorStatusEl.textContent = ""; }}, 2000);
  }}

  /* ── Run TLC button handler ─────────────────────────── */
  btnRunTlc.addEventListener("click", () => {{
    if (!monacoEditor || !liveMode) return;

    const source = monacoEditor.getValue();
    const params = {{}};
    const vals = selectors.map(s => s.value);
    if (vals.some(v => !v)) {{
      editorStatusEl.textContent = "Select all parameters first";
      editorStatusEl.className = "editor-status error";
      return;
    }}
    CONSTANT_NAMES.forEach((name, i) => {{ params[name] = vals[i]; }});

    // UI: running state
    btnRunTlc.classList.add("running");
    btnRunTlc.disabled = true;
    editorStatusEl.textContent = "Running TLC\\u2026";
    editorStatusEl.className = "editor-status";
    errorPanel.classList.remove("active");

    const t0 = performance.now();
    fetch(serverUrl + "/api/trace-custom", {{
      method: "POST",
      headers: {{ "Content-Type": "application/json" }},
      body: JSON.stringify(Object.assign({{ pcal_source: source }}, params)),
    }})
    .then(resp => {{
      return resp.json().then(data => ({{ ok: resp.ok, status: resp.status, data }}));
    }})
    .then(({{ ok, status, data }}) => {{
      btnRunTlc.classList.remove("running");
      btnRunTlc.disabled = false;
      const clientMs = Math.round(performance.now() - t0);

      if (ok) {{
        // Success — cache and render
        const serverMs = data.elapsed_ms || "?";
        const nMsgs = parseTraceFromPuml(data.puml_text).length;
        editorStatusEl.textContent = "\\u2714 TLC passed \\u2014 " + nMsgs + " msgs, " + serverMs + "ms TLC, " + clientMs + "ms total";
        editorStatusEl.className = "editor-status success";
        errorPanel.classList.remove("active");

        // Cache the custom result so switching away and back doesn't re-run TLC
        if (currentKey) CUSTOM_TRACES[currentKey] = data;

        renderTraceData(data);
        elapsedEl.textContent = "Custom TLC: " + serverMs + "ms \\u00b7 round-trip: " + clientMs + "ms";
      }} else {{
        // Error — show in error panel
        const stage = data.stage || "unknown";
        const details = data.details || data.error || "Unknown error";
        editorStatusEl.textContent = "\\u2718 " + (data.error || "TLC failed") + " (" + stage + ")";
        editorStatusEl.className = "editor-status error";
        errorOutput.textContent = details;
        errorPanel.classList.add("active");

        // If server extracted a counterexample trace, render it
        if (data.puml_text && data.error_trace) {{
          const serverMs = data.elapsed_ms || "?";
          renderTraceData(data);
          elapsedEl.textContent = "\\u26a0 ERROR trace: " + serverMs + "ms TLC, " + clientMs + "ms total";
          // Cache so switching away and back preserves the error diagram
          if (currentKey) CUSTOM_TRACES[currentKey] = data;
        }}
      }}
    }})
    .catch(err => {{
      btnRunTlc.classList.remove("running");
      btnRunTlc.disabled = false;
      editorStatusEl.textContent = "\\u2718 " + err.message;
      editorStatusEl.className = "editor-status error";
      errorOutput.textContent = err.message;
      errorPanel.classList.add("active");
    }});
  }});

  /* ── Save PlusCal ────────────────────────────────────── */
  btnSavePcal.addEventListener("click", () => {{
    const source = monacoEditor ? monacoEditor.getValue() : PCAL_SOURCE;
    const blob = new Blob([source], {{ type: "text/plain" }});
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "{pcal_filename}";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    editorStatusEl.textContent = "\u2714 Saved";
    editorStatusEl.className = "editor-status success";
    setTimeout(() => {{ editorStatusEl.textContent = ""; }}, 2000);
  }});

  /* ── Close error panel ──────────────────────────────── */
  btnCloseErr.addEventListener("click", () => {{
    errorPanel.classList.remove("active");
  }});

  /* ── Init ───────────────────────────────────────────── */
  populateLevel(0);
  loadFromUrl();
  updateEditorPaneState();
}})();
</script>

</body>
</html>"""


# ═══════════════════════════════════════════════════════════════════════
# Config-driven entry point (called by build.py)
# ═══════════════════════════════════════════════════════════════════════

def main_build(config) -> None:
    """Build HTML explorer using a PcalConfig object.

    Called by build.py's `cmd_build()`. The caller sets SCRIPT_DIR,
    DISTRIB_DIR, TRACES_DIR, and OUTPUT_HTML before calling this.
    """
    constant_names = config.constant_names

    print(f"\n1. Loading traces from {TRACES_DIR}")
    all_traces = load_traces(constant_names)
    print(f"   {len(all_traces)} PlantUML traces loaded")

    # Build full flow tree from ALL constant combos (not just traces)
    flow_tree = build_full_flow_tree(config)
    top_key = constant_names[0] if constant_names else "flows"
    print(f"   Flow tree: {len(flow_tree)} {top_key} values (all combos)")

    # Compute invalid and skipped combo tag sets for JS
    # Invalid takes priority: skipped set excludes combos already in invalid
    invalid_set = config.expanded_invalid_set()
    invalid_combos = sorted(config.combo_tag(c) for c in invalid_set)
    skipped_combos = sorted(config.combo_tag(c) for c in config.expanded_skip_set() if c not in invalid_set)
    print(f"   {len(invalid_combos)} invalid, {len(skipped_combos)} skipped combos")

    # Compute channel_styles from config
    channels = config.resolve_channels(SCRIPT_DIR)
    config_colors = config.channel_colors or {}
    _PALETTE = [
        ("#2563eb", "→"), ("#16a34a", "→"), ("#dc2626", "→"),
        ("#9333ea", "→"), ("#ea580c", "→"), ("#0891b2", "→"),
        ("#d946ef", "→"), ("#65a30d", "→"),
    ]
    channel_styles = {}
    for i, key in enumerate(channels):
        if key in config_colors:
            cc = config_colors[key]
            stroke = cc.get("stroke", _PALETTE[i % len(_PALETTE)][0])
            label = cc.get("label", _PALETTE[i % len(_PALETTE)][1])
        else:
            stroke, label = _PALETTE[i % len(_PALETTE)]
        channel_styles[key] = {
            "stroke": stroke,
            "label": label,
            "name": key.replace("_", " ").title(),
        }

    pcal_path = SCRIPT_DIR / config.pcal
    pcal_source = pcal_path.read_text(encoding="utf-8") if pcal_path.exists() else ""

    print(f"\n2. Building index.html")
    html = build_html(
        all_traces, flow_tree,
        pcal_source,
        title=config.title,
        branding=config.branding,
        pcal_filename=config.pcal,
        constant_names=constant_names,
        plantuml_server=config.plantuml_server or "",
        tlc_server=config.tlc_server or "http://127.0.0.1:18080",
        channel_styles=channel_styles,
        participants=config.participants,
        invalid_combos=invalid_combos,
        skipped_combos=skipped_combos,
    )

    OUTPUT_HTML.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_HTML.write_text(html, encoding="utf-8")
    size_kb = OUTPUT_HTML.stat().st_size / 1024
    print(f"   Output: {OUTPUT_HTML} ({size_kb:,.0f} KB)")

    # Copy server collateral and create server.zip
    tools_dir = Path(__file__).resolve().parent
    server_files = {
        "tlc_server.py":  tools_dir / "tlc_server.py",
        "tlc_sweep.py":   tools_dir / "tlc_sweep.py",
        "pcal_config.py": tools_dir / "pcal_config.py",
        "tla2tools.jar":  tools_dir / "tla2tools.jar",
    }
    # Model-specific files
    config_file = SCRIPT_DIR / f"{config.module}.explorer.json"
    if config_file.exists():
        server_files[config_file.name] = config_file
    if pcal_path.exists():
        server_files[pcal_path.name] = pcal_path

    # Build server.zip containing everything needed to run tlc_server.py
    zip_path = DISTRIB_DIR / "server.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for arcname, src in server_files.items():
            if src.exists():
                zf.write(src, arcname)
    zip_kb = zip_path.stat().st_size / 1024
    print(f"   Server bundle: {zip_path} ({zip_kb:,.0f} KB)")

    # Build DOCUMENTATION.html from Markdown (search repo root, then model dir)
    doc_md = None
    for candidate in [tools_dir.parent / "DOCUMENTATION.md",
                      SCRIPT_DIR / "DOCUMENTATION.md"]:
        if candidate.exists():
            doc_md = candidate
            break
    if doc_md:
        print(f"\n3. Building DOCUMENTATION.html from {doc_md.name}")
        doc_html = build_documentation_html(
            doc_md,
            title=f"{config.title} — Documentation",
            branding=config.branding,
        )
        doc_out = DISTRIB_DIR / "DOCUMENTATION.html"
        doc_out.write_text(doc_html, encoding="utf-8")
        doc_kb = doc_out.stat().st_size / 1024
        print(f"   Output: {doc_out} ({doc_kb:,.0f} KB)")
    else:
        print("\n3. No DOCUMENTATION.md found — skipping documentation build")


# ═══════════════════════════════════════════════════════════════════════
# CLI
# ═══════════════════════════════════════════════════════════════════════

def parse_args():
    p = argparse.ArgumentParser(description="Build PlusCal Flow Explorer")
    p.add_argument("--serve", action="store_true", help="Start HTTP server after build")
    p.add_argument("--port", type=int, default=18090, help="HTTP server port")
    p.add_argument("--clean", action="store_true",
                   help="Remove generated output (distrib/index.html, distrib/traces/) and exit")
    return p.parse_args()


def main():
    args = parse_args()

    if args.clean:
        removed = []
        if OUTPUT_HTML.exists():
            OUTPUT_HTML.unlink()
            removed.append(str(OUTPUT_HTML))
        if TRACES_DIR.exists():
            shutil.rmtree(TRACES_DIR)
            removed.append(str(TRACES_DIR) + "/")
        if removed:
            print("Cleaned:")
            for r in removed:
                print(f"  {r}")
        else:
            print("Nothing to clean.")
        return

    print("=" * 60)
    print("PlusCal Flow Explorer — Build")
    print("=" * 60)

    # 1. Load traces
    print(f"\n1. Loading traces from {TRACES_DIR}")
    all_traces = load_traces()
    print(f"   {len(all_traces)} PlantUML traces loaded")
    if not all_traces:
        sys.exit("ERROR: No .puml traces found. Run tlc_sweep.py first.")

    # 2. Build flow tree
    # For standalone mode, infer constant_names from trace parameters
    sample_data = next(iter(all_traces.values()))
    constant_names = sorted(sample_data["parameters"].keys())
    flow_tree = build_flow_tree(all_traces, constant_names)
    top_key = constant_names[0] if constant_names else "flows"
    print(f"   Flow tree: {len(flow_tree)} {top_key} values")

    # 3. Load PlusCal source for editor embedding
    pcal_path = SCRIPT_DIR / f"{MODULE}.pcal" if MODULE else None
    pcal_source = ""
    if pcal_path and pcal_path.exists():
        pcal_source = pcal_path.read_text(encoding="utf-8")
        print(f"\n3. Loading PlusCal source from {pcal_path}")
        print(f"   {len(pcal_source):,} bytes ({pcal_source.count(chr(10))} lines)")
    else:
        print(f"\n3. WARNING: {'pcal_path not set' if not pcal_path else f'{pcal_path} not found'} — editor will have empty source")

    # 4. Build HTML
    print(f"\n4. Building index.html …")
    html = build_html(all_traces, flow_tree,
                      pcal_source,
                      pcal_filename=f"{MODULE}.pcal" if MODULE else "model.pcal",
                      constant_names=constant_names)

    OUTPUT_HTML.write_text(html, encoding="utf-8")
    size_kb = OUTPUT_HTML.stat().st_size / 1024
    size_mb = size_kb / 1024
    print(f"   Output: {OUTPUT_HTML}")
    print(f"   Size:   {size_kb:,.0f} KB ({size_mb:.2f} MB)")

    # 5. Create server.zip in distrib/
    print(f"\n5. Creating server.zip in {DISTRIB_DIR}")
    server_files = {
        "tlc_server.py":  SCRIPT_DIR / "tlc_server.py",
        "tlc_sweep.py":   SCRIPT_DIR / "tlc_sweep.py",
        "pcal_config.py": SCRIPT_DIR / "pcal_config.py",
        "tla2tools.jar":  SCRIPT_DIR / "tla2tools.jar",
        f"{MODULE}.explorer.json": SCRIPT_DIR / f"{MODULE}.explorer.json",
        f"{MODULE}.pcal":          SCRIPT_DIR / f"{MODULE}.pcal",
    }
    zip_path = DISTRIB_DIR / "server.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for arcname, src in server_files.items():
            if src.exists():
                zf.write(src, arcname)
                sz = src.stat().st_size / 1024
                print(f"   {arcname} ({sz:,.0f} KB)")
            else:
                print(f"   WARNING: {arcname} not found \u2014 skipping")
    zip_kb = zip_path.stat().st_size / 1024
    print(f"   server.zip ({zip_kb:,.0f} KB)")

    # 6. Build DOCUMENTATION.html via mmd2doc
    doc_md = SCRIPT_DIR / "DOCUMENTATION.md"
    print(f"\n6. Building DOCUMENTATION.html via mmd2doc")
    if doc_md.exists():
        try:
            result = subprocess.run(
                ["iparch-mmd2doc", str(doc_md), "-v", "INFO"],
                capture_output=True, text=True, timeout=120,
                cwd=str(SCRIPT_DIR), **_NOWIN,
            )
            if result.returncode != 0:
                print(f"   WARNING: mmd2doc failed (exit {result.returncode})")
                combined = (result.stdout + result.stderr).strip()
                if combined:
                    for line in combined.splitlines()[-5:]:
                        print(f"   {line}")
            else:
                print(f"   mmd2doc completed successfully")
        except FileNotFoundError:
            print(f"   WARNING: iparch-mmd2doc not found in PATH \u2014 skipping")
        except subprocess.TimeoutExpired:
            print(f"   WARNING: mmd2doc timed out (120s) \u2014 skipping")

        # Copy DOCUMENTATION.html and log files to distrib/
        doc_artifacts = [
            ("DOCUMENTATION.html", False),
            ("DOCUMENTATION.log", False),
        ]
        for name, is_dir in doc_artifacts:
            src = SCRIPT_DIR / name
            dst = DISTRIB_DIR / name
            if src.exists():
                shutil.copy2(src, dst)
                sz = dst.stat().st_size / 1024
                print(f"   {name} ({sz:,.0f} KB)")
            else:
                print(f"   {name} not found \u2014 skipping")

        # Copy mrs/ folder if it exists
        mrs_src = SCRIPT_DIR / "mrs"
        mrs_dst = DISTRIB_DIR / "mrs"
        if mrs_src.is_dir():
            if mrs_dst.exists():
                shutil.rmtree(mrs_dst)
            shutil.copytree(mrs_src, mrs_dst)
            n_files = sum(1 for _ in mrs_dst.rglob("*") if _.is_file())
            print(f"   mrs/ ({n_files} files)")
        else:
            print(f"   mrs/ not found \u2014 skipping")
    else:
        print(f"   WARNING: {doc_md} not found \u2014 skipping")

    # Summary
    print(f"\n{'=' * 60}")
    print(f"  Traces embedded:    {len(all_traces)}")
    print(f"  Constants:          {constant_names}")
    print(f"  Server bundle:      server.zip ({zip_kb:,.0f} KB)")
    print(f"  Documentation:      DOCUMENTATION.html")
    print(f"  Output:             {OUTPUT_HTML.resolve()}")
    print(f"{'=' * 60}")
    print(f"\nDeploy:  cp -r -v {DISTRIB_DIR}/* <destination>/")
    print(f"View:    python -m http.server {args.port} -d {DISTRIB_DIR}")
    print(f"         then open http://localhost:{args.port}")

    if args.serve:
        import os
        os.chdir(str(DISTRIB_DIR))
        print(f"\nServing at http://localhost:{args.port}  (Ctrl+C to stop)")
        httpd = HTTPServer(("", args.port), SimpleHTTPRequestHandler)
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\nShutdown.")


if __name__ == "__main__":
    main()
